# Defaults for all prettier-supported languages.
# Prettier will complete this with settings from .editorconfig file.
bracketSpacing: false
printWidth: 88
proseWrap: always
semi: true
trailingComma: "es5"
# can't use ignore because of https://github.com/prettier/plugin-xml/issues/138
xmlWhitespaceSensitivity: "strict"
